### PR TITLE
PHP 8.3 support added

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by glo71317** [comment]
It seems some issue with infrastructure, 
Screenshot 2023-10-12 at 3 42 06 PM

The error is typically caused by one of the following reasons: An outdated or incompatible version of Node.js or OpenSSL is installed on your system. 
@Ocramius Can you please help regarding this how to proceed on this?

**Comment by glo17680** [comment]
@Ocramius Is there any update on the infrastructure fixes on this PR. Can you please advise ?

**Comment by froschdesign** [comment]
@glo17680 
There are many simple problems that can be solved. For example:

1) [LaminasTest\Crypt\BlockCipher\OpensslAeadTest::testEncryptDecrypt with data set #0 ('gcm')
Creation of dynamic property LaminasTest\Crypt\BlockCipher\OpensslAeadTest::$blockCipher is deprecated](https://github.com/laminas/laminas-crypt/actions/runs/6468938024/job/18073491872?pr=31#step:3:263)
1) [phpunit.xml.dist validates](https://github.com/laminas/laminas-crypt/actions/runs/6468938024/job/18073491872?pr=31#step:3:227)
61) [LaminasTest\Crypt\PublicKey\RsaTest::testVerifyCorruptRaw
Creation of dynamic property LaminasTest\Crypt\PublicKey\RsaTest::$privateKey is deprecated](https://github.com/laminas/laminas-crypt/actions/runs/6468938024/job/18073491872?pr=31#step:3:572)

Any help with this is welcome!

**Comment by froschdesign** [comment]
@glo71317 @glo17680 
Please see the following pull requests for more information on this package:

- #32 
- https://github.com/laminas/technical-steering-committee/pull/155

**Comment by glo71317** [comment]
> @glo71317 @glo17680 Please see the following pull requests for more information on this package:
> 
> * [Allow php 8.3, migrate to phpunit 10 #32](https://github.com/laminas/laminas-crypt/pull/32)
> * [Add abandonment of laminas-crypt to the agenda technical-steering-committee#155](https://github.com/laminas/technical-steering-committee/pull/155)

As per above details this PR is irrelevant now right?

**Comment by weierophinney** [comment]
I pulled your branch locally, and was able to resolve all test failures:

- Changing the algorithm used for factory and `set*Algorithm()` tests to use AES instead of Blowfish (which has been removed from recent editions of OpenSSL).
- Using a MUCH larger prime for DH tests (I grabbed one from the PHP manual).

It looks like we get failures on PHP 8.0, however; I'll see if I can resolve those.

**Comment by weierophinney** [comment]
Failures on PHP 8 were due to some algorithms being unsupported in OpenSSL 3; I've updated tests to skip those algorithms if that version of the library is present.

**Review by gsteel — APPROVED** [review]
LGTM 👍

**Pull request merged**
