### PR TITLE
Allow psr/container v2 [BC Break]

### PR DESCRIPTION
**Pull request by marcelthole**
|    Q          |   A
|-------------- | ------
| BC Break  | yes
| New Feature   | yes

### Description
For a laminas/laminas-servicemanager v4 upgrade this package must allow psr/container v2

The added type hints are allowed for the existing psr/container package v1 and are required for psr/container v2

### CODE REVIEW

**Comment by marcelthole** [comment]
sorry, missed this in #33 😞

**Comment by Ocramius** [comment]
The problem here is that both consumers are not `final`, and this becomes a major BC break.

**Comment by marcelthole** [comment]
oh that's a good point. 
is it okay if i make the classes final and this will be a BC Break?

**Comment by Ocramius** [comment]
IMO yep

**Comment by boesing** [comment]
Please keep in mind that if we release a new major, we should also add a bunch of type-safety.
I know that this will be an additional amount of work but since there are dependants of this component, even from laminas, that would allow us having less new majors everywhere.

So absolutely fine having this in v4 but we should also try to focus on implementing some more BC breaks regarding type-safety.

**Review by gsteel — APPROVED** [review]
Thanks @marcelthole

**Pull request merged**
