### PR TITLE
Replace `container-interop/container-interop`

### PR DESCRIPTION
**Pull request by mlapkin**
Replace deprecated `container-interop/container-interop` with `psr/container`.

### CODE REVIEW

**Comment by djozsef** [comment]
@michalbundyra can we let this PR throught? The test case fails due to an AES CCM tag length setting problem. This problem has nothing to do with `Interop\Container\ContainerInterface` usage defined by `container-interop/container-interop`. As far as my research went.

**Comment by michalbundyra** [comment]
@djozsef 

> The test case fails due to an AES CCM tag length setting problem. This problem has nothing to do with `Interop...`

Can you clarify please what do you mean? What is the problem and why do you wan to get this merged if the problem is somewhere else? Thanks.

**Comment by djozsef** [comment]
@michalbundyra I suppose this PR hasn't been merged beause the test pipeline fails on some PHP versions. The subject of @mlapkin 's PR is to replace the deprecated `container-interop/container-interop` dependency with `psr/container`. He only touched necessary namespace usages and this PR does not cause BC break. So what I say the test failure is not caused by this PR but a more fundamental problems and merging this PR is safe.

Regarding the AES CCM tag length problem I am not sure what is the exact root cause is because I did not dig deep enough. My best bet is that the tag length has to be calculated carefully a must be an exponent of 2, meaning the value `24` [here](https://github.com/laminas/laminas-crypt/blob/master/test/Symmetric/OpensslAeadTest.php#L193) is wrong. But I'd summon @ezimuel here for guidance.

**Comment by djozsef** [comment]
@michalbundyra Sorry I missed some valid BC breaking changes in the PR, that's why I thought it can be merged. NVM.

Regarding the AES CCM tag length problem my best bet is that when encrypting the tag length has to be calculated as an exponent of 2. See `24` [here](https://github.com/laminas/laminas-crypt/blob/master/test/Symmetric/OpensslAeadTest.php#L193).

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)

**Comment by Ocramius** [comment]
See #20 for a better future-proof plan.

**Pull request closed without merging**
